os: osx
osx_image: xcode9.4
language: swift
install: swift package update
script:
- swift test
- swift run builder -h
notifications:
  email: false
  slack:
    rooms:
      secure: RihfNwu4RpSXxgfXmkAwvodIzwz2mm+bz/pkg2prwmNxSQoFI1PD/fjsNZZOyIlvCVMt/5en2aCEgZC9Ix41zIq85qneQVpkZdAazkiS44U6g2Enq9AYPpj2t4O404lv3x562aOt0Z4NJvGMYKBkHXTKwYl4gFjII7Ww2Ss9HhenCkAogpJEg8kma+dK3O8ilfthULDpLjisjHvxfY1mv1tHVpwRQu5mntrdGLDpA+wiXRkwv6aScYrOA3FSXM6BYgXxy2z9Te7nVdtnWQ3lhe6oODTyblDD0ri93vzaEkKa3DOaRCeuChQjmhU24x7GcPCP2YYfL4IYiOTwIExKnu5g79jOa/vnhnCJ0R1RKRYryiUhiDMpLsLT5Pdp0bmNKPXEAGXtfJvnu41Hrl3RJDIjIPHTuXXPUdJ4xe9B45aWOk2vIjGnLmS09EXRkvhDMopVaBQqBXlTTPnEMXEccHte30xCLueVhIfQdMSG8UW8LJvePYtv6ztH47HGOYkHovfUQnLYYHNo0Bzdpf868Ih5dGCoBAApF+HqQsmQ3vOIMudzRf5wOccTjlxRwU9+aD+tiWkAIo8pjax9M9xlpiedqwG8p1GXb+vji7uWUIgzN9HmLfY42fyU5wzj8NG10/ta7b2uQVl49lPiKYRZaV+HD7cQgVshWUOIYseIU14=
